export const brand = {
  name: "Tun Online Armenian School",
  logoUrl: "https://tunapp.com/wp-content/uploads/2020/09/Tun-Logo_Web-Black_80.png",
  faviconUrl: "https://tunapp.com/wp-content/uploads/2020/09/cropped-Tun_Site-Icon-180x180.png",
  footerArtworkUrl: "https://tunapp.com/wp-content/uploads/2026/09/Tun-Footer-Translate__.png",
  colors: {
    primary: "#DB182B",
    primaryDark: "#BF1324",
    background: "#F8F8F8",
    surface: "#FFFFFF",
    ink: "#171717",
    muted: "#666666",
    border: "#E8E5E2",
    strongBorder: "#D6D1CD",
    softAccent: "#FFF0F2",
    success: "#25765A",
    blue: "#0797D3",
  },
  links: {
    lessons: "https://tunapp.com/lessons",
    getStarted: "https://tunapp.com/get-started/",
    shop: "https://tunapp.com/shop",
    socialNetwork: "https://armeniansocialnetwork.com",
    tutoring: "https://tunapp.com/western-armenian-tutoring",
    translator: "https://translatearmenian.com",
    verbs: "https://armenianverbs.com",
    keyboard: "https://armeniankeyboard.com",
    chatbot: "https://tunapp.com/chatbot",
    account: "https://tunapp.com/my-account/",
    downloads: "https://tunapp.com/my-account/downloads/",
    subscriptions: "https://tunapp.com/my-account/subscriptions/",
    paymentMethods: "https://tunapp.com/my-account/payment-methods/",
    passwordRecovery: "https://tunapp.com/login/",
    privacy: "https://tunapp.com/privacy-policy/",
    terms: "https://tunapp.com/website-terms/",
    affiliate: "https://tunapp.com/ambassadors/",
    blog: "https://tunapp.com/blog",
    contact: "mailto:hello@tunapp.com",
    instagram: "https://instagram.com/tun.armenian",
    tiktok: "https://www.tiktok.com/@tun.armenian",
    youtube: "https://www.youtube.com/@TunOnlineArmenianSchool",
  },
} as const;
